version: '3.8'

services:
  next_app:
    image: next_app
    build: .
    container_name: next_app  
    restart: always
    env_file:
      - .env 
    expose:
      - "3000"
    networks:
      - rede_global

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    command: redis-server --save 60 1 --loglevel warning 
    expose:
      - "6379" 
    volumes:
      - redis_data:/data 
    networks:
      - rede_global

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - next_app
    networks:
      - rede_global
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    user: "0"  
    volumes:  
      - /opt/monitoramento/grafana_data:/var/lib/grafana  
    restart: unless-stopped
    networks:
      - rede_global       

volumes:
  redis_data:

networks:
  rede_global:
    name: app-network 
    external: true